// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	frame "github.com/arduino/arduino-cloud-cli/internal/board-protocols/frame"
	mock "github.com/stretchr/testify/mock"

	transport "github.com/arduino/arduino-cloud-cli/internal/board-protocols/transport"
)

// TransportInterface is an autogenerated mock type for the TransportInterface type
type TransportInterface struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *TransportInterface) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connect provides a mock function with given fields: params
func (_m *TransportInterface) Connect(params transport.TransportInterfaceParams) error {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(transport.TransportInterfaceParams) error); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connected provides a mock function with given fields:
func (_m *TransportInterface) Connected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Receive provides a mock function with given fields: timeoutSeconds
func (_m *TransportInterface) Receive(timeoutSeconds int) ([]frame.Frame, error) {
	ret := _m.Called(timeoutSeconds)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 []frame.Frame
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]frame.Frame, error)); ok {
		return rf(timeoutSeconds)
	}
	if rf, ok := ret.Get(0).(func(int) []frame.Frame); ok {
		r0 = rf(timeoutSeconds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]frame.Frame)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(timeoutSeconds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Send provides a mock function with given fields: data
func (_m *TransportInterface) Send(data []byte) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *TransportInterface) Type() transport.InterfaceType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 transport.InterfaceType
	if rf, ok := ret.Get(0).(func() transport.InterfaceType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(transport.InterfaceType)
	}

	return r0
}

// NewTransportInterface creates a new instance of TransportInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransportInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransportInterface {
	mock := &TransportInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
