// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	go_bug_stserial "go.bug.st/serial"

	time "time"
)

// Port is an autogenerated mock type for the Port type
type Port struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Port) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetModemStatusBits provides a mock function with given fields:
func (_m *Port) GetModemStatusBits() (*go_bug_stserial.ModemStatusBits, error) {
	ret := _m.Called()

	var r0 *go_bug_stserial.ModemStatusBits
	if rf, ok := ret.Get(0).(func() *go_bug_stserial.ModemStatusBits); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_bug_stserial.ModemStatusBits)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: p
func (_m *Port) Read(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetInputBuffer provides a mock function with given fields:
func (_m *Port) ResetInputBuffer() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetOutputBuffer provides a mock function with given fields:
func (_m *Port) ResetOutputBuffer() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetDTR provides a mock function with given fields: dtr
func (_m *Port) SetDTR(dtr bool) error {
	ret := _m.Called(dtr)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(dtr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetMode provides a mock function with given fields: mode
func (_m *Port) SetMode(mode *go_bug_stserial.Mode) error {
	ret := _m.Called(mode)

	var r0 error
	if rf, ok := ret.Get(0).(func(*go_bug_stserial.Mode) error); ok {
		r0 = rf(mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetRTS provides a mock function with given fields: rts
func (_m *Port) SetRTS(rts bool) error {
	ret := _m.Called(rts)

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(rts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetReadTimeout provides a mock function with given fields: t
func (_m *Port) SetReadTimeout(t time.Duration) error {
	ret := _m.Called(t)

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Duration) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: p
func (_m *Port) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
