// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onPressureChange();
void onTemperatureChange();

float pressure;
CloudTemperature temperature;

void initProperties(){

  ArduinoCloud.addProperty(pressure, READWRITE, 30 * SECONDS, onPressureChange);
  ArduinoCloud.addProperty(temperature, READWRITE, 30 * SECONDS, onTemperatureChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

